### ISSUE TITLE
Add some information into documentation

### ISSUE THREAD

**Issue by Sinouplen** [groupe-sii/sonar-web-frontend-plugin#20]
Can you specify:
- You can only compiled with JDK and not JRE.
- The directory "sonar-sii-plugin-parent" doesn't exists, but it's the PATH directory of this git project.

**Comment by aurelien-baudet** [comment]
Thank you for the feedback. This is done. Can you check if it is better like this ?

Thanks

**Comment by Sinouplen** [comment]
You have delete my 2nd point.
Why don't you specify to go into the project directory before execute mvn command line?

**Comment by aurelien-baudet** [comment]
I have written it :
"Clone this git repository. _Go into the grabbed folder_"

Maybe it is not enough to understand. What do you suggest ?
