### ISSUE TITLE
Add sonar versions support details

### ISSUE THREAD

**Issue by vogloblinsky** [groupe-sii/sonar-web-frontend-plugin#21]

**Comment by yanzacheus** [comment]
:+1: 
Also how plugins interact...
Only in a sample project I could find informations:
https://github.com/groupe-sii/sonar-web-frontend-helloworld :

> Sonar 4.5.5 LTS with SII sonar plugin installed, Javascript default plugin **uninstalled**

Whatever,  angular eslint report import doesn't work for me:
- with and without the javascript default plugin installed
- with sonarqube version 5.3 and version 4.5.6 LTS

I used default javascript plugin, it works well, but I also wanted to import informations from the eslint-angular plugin. So I wanted to try your plugin...
But it fails to deal with my eslint-angular.json in the report folder:

INFO  - Loading and storing /home/yannick/Depots/rse/report/eslint-angular.json in Sonar
ERROR: failed to parse json file. Cause: Can not deserialize instance of fr.sii.sonar.report.core.quality.domain.report.QualityReport out of START_ARRAY token
 at [Source: java.io.FileInputStream@7c1e32c9; line: 1, column: 1]

I also tried with a default json report provided by eslint :
http://eslint.org/docs/user-guide/formatters/#json
does'nt work neither.

Thanks for your work !

OS: Linux 14.04.1-Ubuntu 
Analyzer: SonarQube Scanner 2.5

**Comment by aurelien-baudet** [comment]
What is generating your eslint-angular.json ?
You need to use our own report generator in order to be understandable by Sonar. It is available here : https://github.com/groupe-sii/sonar-web-frontend-reporters. You need to include in your gulp task. The documentation is missing... We will add it.

The inclusion is done like this (you need to install it through npm install sonar-web-frontend-reporters):

```
var ESReporter = require("../node_modules/sonar-web-frontend-reporters/esLintReporter.js");
    var esReporter = new ESReporter(reportsPath+"eslint-angular.json", basePaths.src);

    gulp.task('ci:es-lint', function() {
        esReporter.openReporter(projectName, projectPath);
            return gulp.src(basePaths.src + '/js/**/*.js')
        .pipe($.eslint({
           reset: true
        }))
        .pipe($.eslint.format(esReporter.reporter))
        //.on('end', esReporter.closeReporter.bind(esReporter));
        ;
    });
```

**Comment by yanzacheus** [comment]
Thanks, effectively, eslint-angular.json generated by the eslint-angular plugin only contained the files array. Using gulp and your eslint task, it works.
But in sonarqube 5.3, If I want to see the results, I must uninstall the javascript plugin from Sonar and then run the analyzer. I can't have both javascript base plugin and your javascript plugin enabled.
And I'd like to keep my reports from the javascript plugin from Sonar...
What could be the best way to do so ? (not to have two projects for one and install/uninstall plugins)
Thanks.

**Comment by aurelien-baudet** [comment]
I close this issue and create a new one for the problem with sonar plugin (#22).
