### ISSUE TITLE
Disable Features?

### ISSUE THREAD

**Issue by jgodi** [groupe-sii/sonar-web-frontend-plugin#25]
Is there a way to disable certain features? For instance I do not need:
- jshint
- csslint
- htmllint
- angular-hint

and a few others.

I also have `sonar.sii.coverage.overall.js.report.path=/coverage/lcov.info` set in my properties file, but inside sonar it says that I do not have any coverage information. Any ideas on that?

Thanks!

**Comment by jgodi** [comment]
Here is the output that I wish to get rid of: 

```
0:25:29.166 WARN  - The report file /home/jenkins/hydrogen/workspace/Novo/Development/find-results/report/jshint.json doesn't exist
10:25:29.166 WARN  - The report file /home/jenkins/hydrogen/workspace/Novo/Development/find-results/report/js-ut.lcov doesn't exist
10:25:29.166 WARN  - The report file /home/jenkins/hydrogen/workspace/Novo/Development/find-results/report/js-ut.lcov doesn't exist
10:25:29.166 WARN  - The report file /home/jenkins/hydrogen/workspace/Novo/Development/find-results/report/js-ut.lcov doesn't exist
10:25:29.166 WARN  - The report file /home/jenkins/hydrogen/workspace/Novo/Development/find-results/report/jasmine.unit.xml doesn't exist
10:25:29.166 WARN  - The report file /home/jenkins/hydrogen/workspace/Novo/Development/find-results/report/jasmine.it.xml doesn't exist
10:25:29.166 WARN  - The report file /home/jenkins/hydrogen/workspace/Novo/Development/find-results/report/js-duplication.xml doesn't exist
10:25:29.166 WARN  - The report file /home/jenkins/hydrogen/workspace/Novo/Development/find-results/report/csslint.json doesn't exist
10:25:29.166 WARN  - The report file /home/jenkins/hydrogen/workspace/Novo/Development/find-results/report/css-duplication.xml doesn't exist
10:25:29.166 WARN  - The report file /home/jenkins/hydrogen/workspace/Novo/Development/find-results/report/htmlhint.json doesn't exist
10:25:29.166 WARN  - The report file /home/jenkins/hydrogen/workspace/Novo/Development/find-results/report/html-duplication.xml doesn't exist
10:25:29.166 WARN  - The report file /home/jenkins/hydrogen/workspace/Novo/Development/find-results/report/scsslint.json doesn't exist
10:25:29.166 WARN  - The report file /home/jenkins/hydrogen/workspace/Novo/Development/find-results/report/scss-duplication.xml doesn't exist
10:25:29.167 WARN  - The report file /home/jenkins/hydrogen/workspace/Novo/Development/find-results/report/angular-hint.json doesn't exist
10:25:29.167 WARN  - The report file /home/jenkins/hydrogen/workspace/Novo/Development/find-results/report/eslint-angular.json doesn't exist
10:25:29.167 INFO  - JaCoCoSensor: JaCoCo report not found : /home/jenkins/hydrogen/workspace/Novo/Development/find-results/target/jacoco.exec
10:25:29.168 INFO  - JaCoCoItSensor: JaCoCo IT report not found: /home/jenkins/hydrogen/workspace/Novo/Development/find-results/target/jacoco-it.exec
```

**Comment by aurelien-baudet** [comment]
Hi,

I added a configuration property for skipping missing file warning:
`sonar.sii.logs.report.missing.skip=true`

Recently, we added support for integration and overall coverage. There was a mistake and it was always the unit test coverage that was loaded. So the overall was not used.

If you don't want some features, you just have to provide no report. For example, if you don't provide jshint.json, the plugin won't generate any information for JSHint.

**Comment by jgodi** [comment]
Awesome, thank you! Do you know why the unit test coverage isn't showing up?

`I also have sonar.sii.coverage.overall.js.report.path=/coverage/lcov.info set in my properties file, but inside sonar it says that I do not have any coverage information.`

**Comment by aurelien-baudet** [comment]
I think, you need both Unit test coverage and Integration test coverage widgets. You may also need to have at least unit test results report in addition to overall coverage. Sonar has some internal computations that need several information in order to display test coverage (it seems that it needs test results too).
Another possibility is that the properties `sonar.sources`and `sonar.tests` are not correctly set and the coverate report information targets files out of the configured scope.
Finally, Sonar makes huge changes between versions and impact plugins developpement. We support only Sonar 4.5.x and try to make it work with Sonar 5.3. All other versions are not tested.

Which Sonar version are you using ?
