### ISSUE TITLE
Are lines of code metrics supported?

### ISSUE THREAD

**Issue by EarthCitizen** [groupe-sii/sonar-web-frontend-plugin#34]
When metrics (for TypeScript) are uploaded to Sonar, I am missing LOC. Is that metric currently supported?

If so, which report would it be collected from?

If not, are there plans to add it?

**Comment by aurelien-baudet** [comment]
Hello,

Yes the LOC metrics is supported until Sonar 4.5.7. For Sonar 5.x, LOC is not supported for now because plugins API have completely changed and need a lot of work.
